name: KPFCNN
ckpt_path: # path/to/your/checkpoint
KP_extent: 1.2
KP_influence: linear
aggregation_mode: sum
architecture:
- simple
- resnetb
- resnetb_strided
- resnetb
- resnetb
- resnetb_strided
- resnetb
- resnetb
- resnetb_strided
- resnetb
- resnetb
- resnetb_strided
- resnetb
- nearest_upsample
- unary
- nearest_upsample
- unary
- nearest_upsample
- unary
- nearest_upsample
- unary
augment_color: 0.8
augment_noise: 0.001
augment_rotation: vertical
augment_scale_anisotropic: true
augment_scale_max: 1.2
augment_scale_min: 0.8
augment_symmetries:
- true
- false
- false
batch_limit: 50000
batch_norm_momentum: 0.02
batch_num: 30
batcher: ConcatBatcher
conv_radius: 2.5
deform_fitting_mode: point2point
deform_fitting_power: 1.0
deform_radius: 6.0
density_parameter: 5.0
first_features_dim: 128
first_subsampling_dl: 0.06
fixed_kernel_points: center
ignored_label_inds: []
in_features_dim: 2 # with colors : 5, without colors : 2
in_points_dim: 3
in_radius: 4.0
lbl_values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
max_in_points: 20000
modulated: false
num_classes: 19 # number of valid classes.
num_kernel_points: 15
num_layers: 5
repulse_extent: 1.2
use_batch_norm: true
val_batch_num: 30
