name: ParisLille3D
dataset_path: # path/to/your/dataset
cache_dir: ./logs/cache
class_weights: [65075320, 33014819, 656096, 61715, 296523, 4052947, 172132,4212295, 10599237]
ignored_label_inds:
- 0
num_points: 65536
test_result_folder: ./test
val_files:
- Lille2.ply
use_cache: False
