name: RandLANet
batcher: DefaultBatcher
ckpt_path: # path/to/your/checkpoint
dim_feature: 8
dim_input: 3 # 3 + feature dimension.
dim_output:
- 16
- 64
- 128
- 256
grid_size: 0.06
ignored_label_inds: []
k_n: 16
num_classes: 19
num_layers: 4
num_points: 45056
sub_sampling_ratio:
- 4
- 4
- 4
- 4