name: Toronto3D
dataset_path: # path/to/your/dataset
cache_dir: ./logs/cache
class_weights: [41697357, 1745448, 6572572, 19136493, 674897, 897825, 4634634, 374721]
ignored_label_inds:
- 0
num_points: 65536
test_files:
- L002.ply
test_result_folder: ./test
train_files:
- L001.ply
- L003.ply
- L004.ply
val_files:
- L002.ply
use_cache: False
